services:
  myapp-main:
    image: jkells/bookapp:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://database-1.cjys2muqsiar.us-east-1.rds.amazonaws.com/deploying2025
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=jordan1234
      - spring.datasource.username=admin